import './style.css';
import heroUrl from './assets/archive-diorama.webp';
import { demoResult } from './generated-demo';

type Page = { title: string; description: string; html: string };

const home: Page = {
  title: 'Media Fidelity Audit — check a media archive',
  description: 'Compare a source folder with a local media archive and save an exact JSON audit report.',
  html: `<section class="hero" aria-labelledby="page-title">
    <div class="hero-copy"><p class="eyebrow">Check an archive without changing your media</p><h1 id="page-title" tabindex="-1">Check your archive against a source folder.</h1><p class="lede">For families and photographers checking a saved copy before clearing an export.</p><div class="actions"><a class="button" href="/demo">Try it with sample data</a><span>See the finished audit after one click.</span></div><ul class="plain-facts"><li>Runs locally with no account.</li><li>Does not change either folder.</li><li>Free under the MIT License.</li></ul></div>
    <figure class="diorama"><img src="${heroUrl}" width="1024" height="1024" fetchpriority="high" alt="A paper source folder and archive box joined by a thread, with a film reel between them." /><figcaption>One source folder, one archive folder, one JSON audit report.</figcaption></figure>
  </section>
  <section class="proof-strip" aria-label="Audit checks"><div><strong>Exact file match</strong><span>SHA-256 in the report</span></div><div><strong>Camera details</strong><span>When the file contains them</span></div><div><strong>Video format and rate</strong><span>When the file contains them</span></div><div><strong>Live Photo media</strong><span>Videos and edit files</span></div></section>
  <section id="preview" class="sample" aria-labelledby="preview-title"><div><p class="eyebrow">A report shows what happened</p><h2 id="preview-title">Find files that need attention.</h2><p>The JSON audit report lists each file’s result, size, exact-match code, and available camera or video details.</p></div><div class="audit-card"><p class="audit-title">Bundled family archive</p><dl><div><dt>Identical</dt><dd class="good">3</dd></div><div><dt>Changed</dt><dd class="warn">1</dd></div><div><dt>Missing</dt><dd class="bad">1</dd></div><div><dt>Live Photo pair</dt><dd>1</dd></div></dl><p class="audit-foot">The sample includes valid JPEG, MOV, HEIC, and XMP files.</p></div></section>
  <section id="how" class="steps" aria-labelledby="how-title"><p class="eyebrow">Three local steps</p><h2 id="how-title">Compare folders you already trust.</h2><ol><li><span>01</span><div><h3>Choose both folders</h3><p>Choose the exported folder as the source and the stored folder as the archive.</p></div></li><li><span>02</span><div><h3>Run the audit</h3><p>The CLI matches relative paths and hashes each source file.</p></div></li><li><span>03</span><div><h3>Keep the JSON report</h3><p>Review changed, missing, moved, or archive-only paths.</p></div></li></ol></section>
  <section id="install" class="install" aria-labelledby="install-title"><div><p class="eyebrow">Install from the public source checkout</p><h2 id="install-title">Run your first audit.</h2><p>Requires Rust 1.85 or newer.</p></div><div class="terminal" role="region" tabindex="0" aria-label="Terminal command example"><code><span>$</span> git clone https://github.com/B-Divyesh/sf-media-fidelity-audit.git<br><span>$</span> cd sf-media-fidelity-audit<br><span>$</span> cargo install --path .<br><span>$</span> mfa audit --source /CameraExport \\<br>&nbsp;&nbsp;--archive /PhotoArchive --output manifest.json</code><button class="copy" type="button" data-copy="cargo install --path .">Copy install command</button><p class="copy-status" aria-live="polite"></p></div></section>
  <section id="limits" class="limits" aria-labelledby="limits-title"><p class="eyebrow">Clear limits</p><h2 id="limits-title">It checks bytes, not picture quality.</h2><p>Matching hashes prove matching bytes. They do not judge focus, colour, or composition.</p><p>By default it matches relative paths. Add <code>--find-moved</code> to report byte-identical archive files stored elsewhere.</p></section>`,
};
const demo: Page = {
  title: 'Demo — Media Fidelity Audit', description: 'Review a valid bundled media sample and the JSON result made by the mfa demo command.',
  html: `<aside class="demo-banner" aria-label="Demo mode"><strong>Demo — sample data, nothing is saved</strong><span>This page stores nothing; <code>mfa demo</code> uses a temporary folder.</span><button type="button" data-reset-demo>Reset demo</button><a href="/#install">View install steps</a></aside><section class="demo-page" aria-labelledby="page-title"><p class="eyebrow">Bundled command-line demo</p><h1 id="page-title" tabindex="-1">Review a sample archive audit.</h1><p class="lede">Five valid media files show an identical, changed, and missing result.</p><div class="audit-card demo-summary"><p class="audit-title">Sample result</p><dl><div><dt>Identical</dt><dd class="good">${demoResult.summary.matched}</dd></div><div><dt>Changed</dt><dd class="warn">${demoResult.summary.changed}</dd></div><div><dt>Missing</dt><dd class="bad">${demoResult.summary.missing}</dd></div><div><dt>Live Photo pairs</dt><dd>${demoResult.summary.live_photo_pairs}</dd></div></dl></div><div class="terminal demo-terminal" role="region" tabindex="0" aria-label="Recorded output from mfa demo"><code><span>$</span> mfa demo<br>Demo — bundled sample data; your media is never read or changed.<br><br>Media Fidelity Audit<br>&nbsp;&nbsp;${demoResult.summary.source_files} source files · ${demoResult.summary.matched} identical · ${demoResult.summary.changed} changed<br>&nbsp;&nbsp;${demoResult.summary.missing} missing · ${demoResult.summary.moved} moved · ${demoResult.summary.unreadable} unreadable<br>&nbsp;&nbsp;manifest: /tmp/mfa-demo…/sample-manifest.json</code></div><div class="demo-grid"><div><h2>Files in the sample</h2><ul class="file-list">${demoResult.assets.map(asset => `<li><code>${asset.relative_path.split('/').at(-1)}</code> — ${asset.status.replace('_', ' ')}</li>`).join('')}</ul></div><div><h2>Run it yourself</h2><div class="command-row"><code>cargo run -- demo</code><button class="copy" type="button" data-copy="cargo run -- demo">Copy demo command</button></div><p class="copy-status" aria-live="polite"></p></div></div></section>`,
};
const privacy: Page = { title: 'Privacy — Media Fidelity Audit', description: 'How Media Fidelity Audit keeps archive checks local.', html: `<article class="legal" aria-labelledby="page-title"><p class="eyebrow">Policy</p><h1 id="page-title" tabindex="-1">Privacy</h1><p>The CLI reads content from the source and archive folders you choose.</p><p>The CLI has no account system or network dependency.</p><p>The static website sends no third-party requests and stores no browser data during its demo.</p><h2>Questions</h2><p><a href="https://github.com/B-Divyesh/sf-media-fidelity-audit">Open the GitHub source repository (external)</a>.</p></article>` };
const terms: Page = { title: 'Terms — Media Fidelity Audit', description: 'Terms for using Media Fidelity Audit.', html: `<article class="legal" aria-labelledby="page-title"><p class="eyebrow">Terms</p><h1 id="page-title" tabindex="-1">Terms</h1><p>Media Fidelity Audit is provided under the MIT License.</p><p>It is a verification aid, not a replacement for backups or manual review.</p><p>Hashes establish byte equality. They do not establish image quality or fitness for a purpose.</p><p>You are responsible for choosing the correct source and archive folders.</p></article>` };
const notFound: Page = { title: 'Page not found — Media Fidelity Audit', description: 'The requested Media Fidelity Audit page was not found.', html: `<section class="not-found" aria-labelledby="page-title"><div class="lost-thread" aria-hidden="true"></div><p class="eyebrow">404 · Thread lost</p><h1 id="page-title" tabindex="-1">This archive path is missing.</h1><p>The page may have moved, but your media has not been touched.</p><a class="button" href="/">Return home</a></section>` };
const routes: Record<string, Page> = { '/': home, '/demo': demo, '/privacy': privacy, '/terms': terms, '/404': notFound };
const main = document.querySelector<HTMLElement>('#main')!; const announcement = document.querySelector<HTMLElement>('.route-status')!;
function setMeta(name: string, content: string) { document.querySelector<HTMLMetaElement>(name)?.setAttribute('content', content); }
function render(focus = false) { const path = location.pathname.replace(/\/$/, '') || '/'; const demoQuery = path === '/' && new URLSearchParams(location.search).get('demo') === '1'; const page = demoQuery ? demo : routes[path] || notFound; const canonicalPath = demoQuery ? '/demo' : path; main.innerHTML = page.html; document.title = page.title; document.querySelector<HTMLMetaElement>('meta[name="description"]')!.content = page.description; document.querySelector<HTMLLinkElement>('link[rel="canonical"]')!.href = `https://media-fidelity-audit.sociobot.in${canonicalPath === '/' ? '/' : canonicalPath}`; setMeta('meta[property="og:title"]', page.title); setMeta('meta[property="og:description"]', page.description); setMeta('meta[name="twitter:title"]', page.title); setMeta('meta[name="twitter:description"]', page.description); announcement.textContent = page.title; bindActions(); if (focus) document.querySelector<HTMLElement>('h1')?.focus(); }
function bindActions() { document.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(button => button.addEventListener('click', async () => { const status = button.closest('div')?.querySelector<HTMLElement>('.copy-status') || document.querySelector<HTMLElement>('.copy-status'); try { await navigator.clipboard.writeText(button.dataset.copy!); if (status) status.textContent = 'Command copied.'; } catch { if (status) status.textContent = 'Select the command and copy it manually.'; } })); document.querySelector<HTMLButtonElement>('[data-reset-demo]')?.addEventListener('click', () => { render(false); const banner = document.querySelector<HTMLElement>('.demo-banner'); if (banner) { banner.tabIndex = -1; banner.focus(); } announcement.textContent = 'Demo reset to the bundled sample.'; }); }
document.addEventListener('click', event => { const link = (event.target as Element).closest<HTMLAnchorElement>('a[href]'); if (!link || link.origin !== location.origin || link.target || link.hasAttribute('download')) return; const target = new URL(link.href); if (target.pathname === location.pathname && target.hash) return; event.preventDefault(); history.pushState({}, '', target.pathname + target.hash); render(true); if (target.hash) document.querySelector(target.hash)?.scrollIntoView(); else scrollTo(0, 0); }); window.addEventListener('popstate', () => render(true)); render(false);
